// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhTcbFbkVDal4D-Dde9Dnr7pvsSF0Svk',
    appId: '1:659899360025:web:8ab234cbb0373093535b88',
    messagingSenderId: '659899360025',
    projectId: 'onuche-david-a022f',
    authDomain: 'onuche-david-a022f.firebaseapp.com',
    storageBucket: 'onuche-david-a022f.firebasestorage.app',
    measurementId: 'G-GJVVV3BFC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZl2SXbARxMogCw5GyGFHwIzltt0SGa_M',
    appId: '1:659899360025:android:606070b865c64dc2535b88',
    messagingSenderId: '659899360025',
    projectId: 'onuche-david-a022f',
    storageBucket: 'onuche-david-a022f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOvw0vlkA_owmJUobKxJY5lb8wdkLjXx4',
    appId: '1:659899360025:ios:54c706a80b25baf4535b88',
    messagingSenderId: '659899360025',
    projectId: 'onuche-david-a022f',
    storageBucket: 'onuche-david-a022f.firebasestorage.app',
    iosBundleId: 'com.example.onucheDavid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOvw0vlkA_owmJUobKxJY5lb8wdkLjXx4',
    appId: '1:659899360025:ios:54c706a80b25baf4535b88',
    messagingSenderId: '659899360025',
    projectId: 'onuche-david-a022f',
    storageBucket: 'onuche-david-a022f.firebasestorage.app',
    iosBundleId: 'com.example.onucheDavid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZhTcbFbkVDal4D-Dde9Dnr7pvsSF0Svk',
    appId: '1:659899360025:web:261731d7f0fe4c36535b88',
    messagingSenderId: '659899360025',
    projectId: 'onuche-david-a022f',
    authDomain: 'onuche-david-a022f.firebaseapp.com',
    storageBucket: 'onuche-david-a022f.firebasestorage.app',
    measurementId: 'G-0ZRDET1FD5',
  );

}